# Generated by Django 4.1.2 on 2022-10-12 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flex', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flexpage',
            options={},
        ),
        migrations.AddField(
            model_name='flexpage',
            name='texte',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
